site_name: Kinlau's Blog
site_url: https://mydomain.org/mysite

#导航栏设置
nav:
  #类别
  - Work: 
      - work/index.md
      - 通识: 
        - work/work.md
  - RM:
    - RM/机械组自学内容一览.md
    - 培训:
      - RM/PPT/Lec.01材料与工艺培训.md
      - RM/PPT/Lec.02传动.md
      - RM/PPT/Lec.03轴系.md
      - RM/PPT/Lec.04专用零件设计及加工原理.md
      - RM/PPT/Lec.05动力元件-机架-总体设计.md

  - ISEE: 
      - Study/ISEE/index.md
      - 场波:
        - Study/ISEE/场波/index.md
        - Study/ISEE/场波/场波.md
        - Study/ISEE/场波/麦克斯韦方程组.md
      - 信号与系统:
        - Study/ISEE/信号与系统/导览.md
        - Study/ISEE/信号与系统/Lec01-基础导论.md
        - Study/ISEE/信号与系统/Lec02-DT&CT.md
        - Study/ISEE/信号与系统/Lec03-Feedback.md
  #- 学习:
      # - study/index.md
      # - 通识: 
        
      
          
  - EMM: 
    - 前言: EMM/index.md
    - 总览: EMM/Contents.md
    - 保送: 
        #- EMM/University/index.md
        - 收录名单: 
          - 2022届: EMM/University/保送名单/2022届.md
          - 2023届: EMM/University/保送名单/2023届.md
          - 2024届: EMM/University/保送名单/2024届.md
          - 2025届: EMM/University/保送名单/2025届.md
          - 2026届: EMM/University/保送名单/2026届.md
        - 联招材料:
          - 2023届: EMM/University/保送材料/2023届.md
          - 2024届: EMM/University/保送材料/2024届.md
          - 2025届: EMM/University/保送材料/2025届.md
          - 2026届: EMM/University/保送材料/2026届.md

        
    - 奖/助学金: 
        #- EMM/Scholarship/index.md
        - 澳门奖/助学金:  EMM/Scholarship/澳门.md
        - 国内奖/助学金:  EMM/Scholarship/国内.md
        
  - Tag: tag.md

  - Else: 
    - Else/test.md



#[UI]界面设置
theme:
  name: material
  #改变语言
  language: zh
  #切换主题颜色
  palette:
     # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
        primary: grey
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        primary: grey
  #改变字体
  font:
    text: Roboto
  features: 
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.instant 
    #- header.autohide  #自动隐藏
    - navigation.instant.progress
    # - navigation.prune #渲染的 HTML 中仅包含可见的导航项
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    #- navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    #- navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    - content.code.select
    - content.action.edit
    - content.action.view
    - content.code.annotate 
    - content.action.edit # 编辑按钮
    - content.action.view # 查看源代码按钮
    - content.code.copy # 支持代码块复制
    - navigation.footer # 上一页和下一页
    - navigation.tabs # 一级导航在横着的导航栏
    - content.code.annotate # 可以在代码块中增添点击展示的注释，参见 https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    # - navigation.tracking # 地址栏中的 URL 会随当前位置变化为对应小节的 URL
    - navigation.indexes # 将 index 页面直接附到小节名上
    - navigation.top # 回到顶部按钮
    # - navigation.sections # 二级导航是粗体
    # - navigation.expand # 导航默认展开
    - toc.follow # toc 跟随
    # - toc.integrate # 文档 toc 集成到总目录中 
    - search.suggest
    - search.highlight
    - search.share
    
#插件设置
plugins:
  - blog:
      post_date_format: full #时间
      draft: true
      draft_if_future_date: true #自动将具有未来日期的帖子标记为草稿
      post_readtime: true
      post_readtime_words_per_minute: 265  #计算帖子的阅读时间时读者每分钟预计阅读的字数
      post_url_format: "{date}/{slug}"
      # categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
      # categories_toc: true
      # pagination_per_page: 5
      pagination_url_format: "page/{page}"
  
  - tags:
      tags_file: tag.md  #分类标签

  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

  - offline

 
#右上角搜索设置
#edit_uri: edit/main/docs # 编辑按钮跳转的链接 
#repo_url: https://github.com/Kinlauu/mkdocs # 右上角点击跳转的链接
#repo_name: Kinlauu.github.io # 右上角的名字

#markdown扩展
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  # - callouts
  - md_in_html
  - markdown.extensions.abbr # 支持Markdown文件上方自定义标题标签等
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format 
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true


  
extra_javascript:
  # - javascripts/extra.js 
  # - javascripts/bannerSlider.js
  - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/javascripts/extra.js  # extra的cdn
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/geren.js
  - javascripts/mathjax-config.js
  # - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML
  # - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js
  # - https://cdnjs.cloudflare.com/ajax/libs/social-share.js/1.0.16/js/social-share.min.js
  # - javascripts/backbound1.js
  # - https://cdn.jsdelivr.net/npm/mermaid@10.0.2/dist/add-html-label-6e56ed67.min.js
  # - https://res.zvo.cn/translate/translate.js  # Translate
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


extra_css:
  - stylesheets/extra.css
  - stylesheets/extra2.css  
  #- stylesheets/link.css  #友链
  #- stylesheets/customize.css  #按钮圆角化
  # - stylesheets/flink.css
  # - assets/stylesheets/portfolio.css #个人简历 
  - stylesheets/bannerSlider.css
  # - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/stylesheets/extra.css # extra.css的CDN
  # - stylesheets/extra1.css
  # - stylesheets/video.css
  # - https://unpkg.com/@waline/client@v2/dist/waline.css
  # - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.css #评论
  # - ckplayer/css/ckplayer.css
  # - https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css
  # - https://cdnjs.cloudflare.com/ajax/libs/social-share.js/1.0.16/css/share.min.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css  #字体 
  # - https://chinese-fonts-cdn.deno.dev/packages/lxgwwenkai/dist/LXGWWenKai-Bold/result.css

# watch:
#   - docs
#   - mkdocs.yml
#   - docs/overrides
